flag_management:
  default_rules:
    carryforward: true
coverage:
  status:
    project:
      default:
        target: 75%
      store:
        flags:
          - store
      notification:
        flags:
          - notification
      accounts:
        flags:
          - accounts
flags:
  store:
    paths:
      - services/store
  notification:
    paths:
      - services/notification
  accounts:
    paths:
      - services/accounts
