export const templates = {
  review: {
    errorMessage: {
      required: {
        application_icon: 'application icon is required and should be a valid link',
        application_title: 'application title is required',
        content: 'content is required',
        country_id: 'country id is required',
        review_url: 'review url is required and should be a valid link',
        score: 'score is required and should be between 1 and 5',
        sent_at: 'sent at date is required',
        title: 'title is required',
        username: 'username is required',
      },
      type: 'should be an object',
    },
    properties: {
      application_icon: { format: 'url', type: 'string' },
      application_title: { type: 'string' },
      content: { type: 'string' },
      country_id: { type: 'string' },
      review_url: { format: 'url', type: 'string' },
      score: { maximum: 5, minimum: 1, type: 'number' },
      sent_at: { format: 'date-time', type: 'string' },
      title: { type: 'string' },
      username: { type: 'string' },
    },
    required: [
      'username',
      'title',
      'content',
      'country_id',
      'score',
      'sent_at',
      'application_title',
      'application_icon',
      'review_url',
    ],
    type: 'object',
  },
}
