replicaCount: 5
strategyType: RollingUpdate
podAnnotations:
  linkerd.io/inject: enabled
  config.linkerd.io/trace-collector: linkerd-collector.linkerd:55678
  config.alpha.linkerd.io/trace-collector-service-account: linkerd-collector
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
gitlab:
  app: subscription
  env: prod
  envName: production
  envURL: https://subscription.socketkit.com
service:
  enabled: true
  annotations: {}
  name: subscription
  type: ClusterIP
  url: https://subscription.socketkit.com
  externalPort: 3001
  internalPort: 3001
ingress:
  enabled: false
prometheus:
  metrics: true
livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 60
  probeType: 'exec'
  command: ["/bin/grpc_health_probe", "-addr=:3001"]
readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 60
  probeType: 'exec'
  command: ["/bin/grpc_health_probe", "-addr=:3001"]
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: false
