replicaCount: 1
strategyType: RollingUpdate
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
gitlab:
  app: store
  env: prod
  envName: production
  envURL: https://store.socketkit.com
service:
  enabled: true
  annotations: {}
  name: store
  type: ClusterIP
  url: https://store.socketkit.com
  externalPort: 3003
  internalPort: 3003
ingress:
  enabled: false
livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 15
  probeType: 'exec'
  command: ["/bin/grpc_health_probe", "-addr=:3003"]
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 15
  probeType: 'exec'
  command: ["/bin/grpc_health_probe", "-addr=:3003"]
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: false
