{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "sharedlabels" . | indent 4}}
spec:
{{ toYaml .Values.networkPolicy.spec | indent 2 }}
{{- end -}}
