name: Publish

on:
  release:
    types: [published]
strategy:
  matrix:
    worker_name: [store, accounts]

jobs:
  push_to_github:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        id: release
        run: |
          version=$(echo ${{github.event.release.tag_name}} | sed 's/${{matrix.worker_name}}\///g')
          echo "::set-output name=version::$version"

      - name: Build container image
        uses: docker/build-push-action@v2
        working-directory: services/${{ matrix.worker_name }}
        if: ${{ startsWith(github.event.release.tag_name, matrix.worker_name) }}
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/${{ matrix.worker_name }}:${{ steps.release.outputs.version }}
            docker.pkg.github.com/${{ github.repository }}/${{ matrix.worker_name }}:latest
