replicaCount: 1
strategyType: RollingUpdate
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app: core
  env: prod
  envName: production
  envURL: https://core.socketkit.com
service:
  enabled: true
  annotations: {}
  name: core
  type: ClusterIP
  url: https://core.socketkit.com
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: true
  path: "/"
  tls:
    secretName: "core-tls"
  annotations: {}
livenessProbe:
  path: "/health"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/health"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: false
