replicaCount: 1

image:
  repository: "registry.gitlab.com/socketkit/core"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: "core-registry"
nameOverride: "core"
fullnameOverride: "core"

serviceAccount:
  create: true
  annotations: {}
  name: "core-account"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: core.socketkit.com
      paths:
      - path: /
        backend:
          serviceName: core
          servicePort: 3000
  tls:
   - secretName: "core-tls"
     hosts:
       - core.socketkit.com

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

application:
  secretName: "core-environment"
